### ISSUE TITLE
new svg_fmt release?

### ISSUE THREAD

**Issue by problame** [nical/rust_debug#5]
In https://github.com/neondatabase/neon/issues/7763 we're waiting for a new `svg_fmt` release; we're currently using

```
svg_fmt = { git = "https://github.com/nical/rust_debug", rev = "28a7d96eecff2f28e75b1ea09f2d499a60d0e3b4" }
```

to get our earlier contribution of https://github.com/nical/rust_debug/commit/28a7d96eecff2f28e75b1ea09f2d499a60d0e3b4

---

Could you publish a new svg_fmt release?

Much Appreciated!

**Comment by nical** [comment]
Hi! it looks like the commit you are referencing is already on crates.io (in version 0.4.3).

**Comment by problame** [comment]
Hm, yeah, indeed it i.

I guess I was confused because it's still 0.4.2 on github (?)

https://github.com/nical/rust_debug/blob/04148b9c5437ea3bf6fe630cf5146db5f8317de6/svg_fmt/Cargo.toml#L3

**Comment by nical** [comment]
Indeed, that's both odd and confusing, thanks for pointing it out!
